version: '3.8'
services:
  web:
    build: .
    container_name: guessing_game
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=game.py
      - FLASK_ENV=development
    command: python game.py
